# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms
# File created using:
#
# conda env export --from-history
#
# with otter-grader manually added.
name: dsc80
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip==23.2.1
  - matplotlib==3.5.1
  - numpy==1.21.2
  - notebook==6.4.12
  - pandas==1.3.3
  - pillow==8.3.2
  - pydantic==1.8.2
  - pyyaml==6.0.1
  - requests==2.31.0
  - tqdm==4.62.3
  - urllib3==1.26.7
  - scikit-learn==1.0.2
  - seaborn==0.11.2
  - beautifulsoup4==4.10.0
  - statsmodels==0.13.5
  - plotly==5.17.0
  - jupyterlab==4.0.6
  - nbconvert==7.8.0
  - docopt==0.6.2
  - pytest-xdist==3.3.1
  - sqlalchemy==2.0.21
  - ca-certificates
  - openssl
  - lxml==4.9.4 
  - pip:
    - otter-grader==3.1.4
    - pandas_tutor

